### ISSUE TITLE
[Feature Request]: Feat: Synced Lyrics- Add font size & animation speed toggle

### ISSUE THREAD

**Issue by Rairof** [th-ch/youtube-music#2816]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Adding toggles for users to set the font size and synced lyrics animation speed.

### Proposed Solution

Font size and sentence syncing animation being user configurable-
![image](https://github.com/user-attachments/assets/2b4dc916-77d3-4fed-a452-06f441c2579c)

### Alternatives Considered

N/A

### Additional Information

Would be nice to have such configurations for different type of monitors and layouts and also giving the users the choice to set how bit the font they want it to be and how speedy they want the animation to be.

**Comment by ValiantZippu** [comment]
Also a toggle for spacing between each lyric

( Nice idea )

**Comment by joulev** [comment]
Agreed. The current lyrics is too small imo, and the lines are too far apart. And I can't control the lyrics font size because it is already hardcoded with `!important`, nullifying all changes my custom CSS file brings to it.

**Comment by uvw** [comment]
> Agreed. The current lyrics is too small imo, and the lines are too far apart. And I can't control the lyrics font size because it is already hardcoded with `!important`, nullifying all changes my custom CSS file brings to it.

I was able to change the font size and padding with custom CSS. Here is mine, for example:
```css
/*
Lyrics Typography:
Source CSS: https://github.com/th-ch/youtube-music/blob/master/src/plugins/synced-lyrics/style.css
*/
#synced-lyrics-container .text-lyrics.description {
  /* default: center */
  --lyrics-text-align: left !important;

  /* default: clamp(1.4rem, 1.1vmax, 3rem) */
  --lyrics-font-size: clamp(2rem, 2vmax, 4rem) !important;

  /* default: 2rem */
  --lyrics-padding: .8rem !important;

  /* Override these directly because .description does not use vars defined in its style.css */
  font-size: var(--lyrics-font-size) !important;
  text-align: var(--lyrics-text-align) !important;
}
```
